export const ARTICLES = {
  headerPaddingY: 38,
  headerPaddingX: 24,
  headerPaddingYTablet: 20,
  headerPaddingXTablet: 12,
  headerPaddingYMobile: 16,
  headerPaddingXMobile: 12,
  bodyPadding: 24,
  bodyPaddingYForm: 38,
  bodyPaddingCompact: 12,
  contentGap: 16,
  contentGapTablet: 12,
  tableMinWidth: 760,
  colIndexWidth: 72,
  colActionsWidth: 64,
  cardGap: 12,
  cardGapMobile: 8,
  cardPadding: 16,
  cardPaddingMobile: 12,
  cardIndexPaddingX: 6,
  cardIndexRadius: 6,
  cardMetaLabelWidth: 72,
  formLayoutGap: 24,
  formFieldsGap: 12,
  formTagsWidth: 280,
  formTagsListMaxHeight: 360,
  deleteStatusGap: 16,
} as const;

export const ARTICLES_VAR = {
  headerPaddingY: "var(--articles-header-padding-y)",
  headerPaddingX: "var(--articles-header-padding-x)",
  bodyPadding: "var(--articles-body-padding)",
  contentGap: "var(--articles-content-gap)",
  tableMinWidth: "var(--articles-table-min-width)",
  formTagsWidth: "var(--articles-form-tags-width)",
  formTagsListMaxHeight: "var(--articles-form-tags-list-max-height)",
} as const;
