export const TABLE = {
  rowHeight: 48,
  headerBg: "#F0F0F0",
  stroke: "#E6E6E6",
  strokeWidth: 1,
  rowBg: "#FFFFFF",
  rowNumberBg: "#F0F0F0",
  rowNumberRadius: 4,
  rowNumberSize: 28,
  rowNumberPaddingX: 8,
  headerFontSize: 18,
  headerLineHeight: 24,
  cellFontSize: 14,
  cellLineHeight: 20,
  cellPaddingX: 16,
  actionsTriggerSize: 32,
  actionsTriggerRadius: 12,
  actionsTriggerBorderWidth: 1,
  actionsMenuWidth: 144,
  actionsMenuHeight: 90,
  actionsMenuPadding: 8,
  actionsMenuGap: 4,
  actionsMenuRadius: 12,
  actionsMenuEdge: 8,
  actionsMenuShadow: "0px 4px 16px rgba(0, 0, 0, 0.16)",
} as const;

export const TABLE_VAR = {
  rowHeight: "var(--table-row-height)",
  headerBg: "var(--table-header-bg)",
  stroke: "var(--table-stroke)",
  strokeWidth: "var(--table-stroke-width)",
  rowBg: "var(--table-row-bg)",
  rowNumberBg: "var(--table-row-number-bg)",
  rowNumberRadius: "var(--table-row-number-radius)",
  rowNumberSize: "var(--table-row-number-size)",
  rowNumberPaddingX: "var(--table-row-number-padding-x)",
  headerFontSize: "var(--table-header-font-size)",
  headerLineHeight: "var(--table-header-line-height)",
  cellFontSize: "var(--table-cell-font-size)",
  cellLineHeight: "var(--table-cell-line-height)",
  cellPaddingX: "var(--table-cell-padding-x)",
  actionsTriggerSize: "var(--table-actions-trigger-size)",
  actionsTriggerRadius: "var(--table-actions-trigger-radius)",
  actionsTriggerBorderWidth: "var(--table-actions-trigger-border-width)",
  actionsMenuWidth: "var(--table-actions-menu-width)",
  actionsMenuHeight: "var(--table-actions-menu-height)",
  actionsMenuPadding: "var(--table-actions-menu-padding)",
  actionsMenuGap: "var(--table-actions-menu-gap)",
  actionsMenuRadius: "var(--table-actions-menu-radius)",
  actionsMenuEdge: "var(--table-actions-menu-edge)",
  actionsMenuShadow: "var(--table-actions-menu-shadow)",
} as const;
