export type TokenKind = "color" | "size" | "type" | "shadow" | "motion" | "z" | "other";

export type TokenEntry = {
  name: string;
  value: string;
  description: string;
  kind: TokenKind;
};

export type TokenCategorySlug =
  | "colors"
  | "typography"
  | "spacing"
  | "radius"
  | "motion"
  | "elevation"
  | "input"
  | "checkbox"
  | "button"
  | "toast"
  | "pagination"
  | "menu"
  | "modal"
  | "section"
  | "sidebar"
  | "header"
  | "table"
  | "login"
  | "dashboard"
  | "articles"
  | "docs";

export type TokenCategory = {
  slug: TokenCategorySlug;
  title: string;
  description: string;
  group: "Foundations" | "Components";
  tokens: readonly TokenEntry[];
};

export const TOKEN_NAV: readonly TokenCategory[] = [
  {
    slug: "colors",
    title: "Colors",
    description: "Neutral, primary, success, error, and product color roles.",
    group: "Foundations",
    tokens: [
      { name: "--neutral-fg1-default", value: "#333333", description: "Primary text / icons.", kind: "color" },
      { name: "--neutral-fg1-hover", value: "#191919", description: "Primary text on hover.", kind: "color" },
      { name: "--neutral-fg1-press", value: "#000000", description: "Primary text on press.", kind: "color" },
      { name: "--neutral-fg1-disable", value: "#cccccc", description: "Disabled text / icons.", kind: "color" },
      { name: "--neutral-fg2-default", value: "#7f7f7f", description: "Secondary / muted text.", kind: "color" },
      { name: "--neutral-fg3-default", value: "#ffffff", description: "Text on filled primary surfaces.", kind: "color" },
      { name: "--neutral-bg1-default", value: "#ffffff", description: "Default surface background.", kind: "color" },
      { name: "--neutral-bg1-hover", value: "#f0f0f0", description: "Surface hover background.", kind: "color" },
      { name: "--neutral-bg1-press", value: "#ebebeb", description: "Surface press background.", kind: "color" },
      { name: "--neutral-st1-default", value: "#7f7f7f", description: "Strong stroke.", kind: "color" },
      { name: "--neutral-st1-hover", value: "#666666", description: "Strong stroke hover.", kind: "color" },
      { name: "--neutral-st1-press", value: "#4c4c4c", description: "Strong stroke press.", kind: "color" },
      { name: "--neutral-st2-default", value: "#cccccc", description: "Default field / control stroke.", kind: "color" },
      { name: "--neutral-st2-hover", value: "#b3b3b3", description: "Default stroke hover.", kind: "color" },
      { name: "--neutral-st2-press", value: "#999999", description: "Default stroke press.", kind: "color" },
      { name: "--neutral-st2-disable", value: "#cccccc", description: "Disabled stroke.", kind: "color" },
      { name: "--neutral-st3-default", value: "#E6E6E6", description: "Subtle divider stroke.", kind: "color" },
      { name: "--primary-fg1-default", value: "#009595", description: "Primary brand text / links.", kind: "color" },
      { name: "--primary-fg1-hover", value: "#007070", description: "Primary text hover.", kind: "color" },
      { name: "--primary-bg1-default", value: "#E0F7F7", description: "Soft primary fill.", kind: "color" },
      { name: "--primary-bg1-hover", value: "#D6F4F4", description: "Soft primary hover.", kind: "color" },
      { name: "--primary-bg2-default", value: "#009595", description: "Solid primary fill.", kind: "color" },
      { name: "--primary-bg2-hover", value: "#007070", description: "Solid primary hover.", kind: "color" },
      { name: "--primary-bg2-press", value: "#004a4a", description: "Solid primary press.", kind: "color" },
      { name: "--primary-bg2-disable", value: "#99e3e3", description: "Solid primary disabled.", kind: "color" },
      { name: "--success-fg1-default", value: "#17B24A", description: "Success text / icons.", kind: "color" },
      { name: "--success-bg1-default", value: "#E3F6E9", description: "Success soft fill.", kind: "color" },
      { name: "--error-fg1-default", value: "#d61e20", description: "Error text / icons.", kind: "color" },
      { name: "--error-bg1-default", value: "#FAE4E4", description: "Error soft fill.", kind: "color" },
      { name: "--error-bg2-default", value: "#d61e20", description: "Solid error / danger fill.", kind: "color" },
      { name: "--error-bg2-hover", value: "#ab181a", description: "Solid error hover.", kind: "color" },
      { name: "--error-bg2-press", value: "#801213", description: "Solid error press.", kind: "color" },
      { name: "--error-bg2-disable", value: "#efa5a6", description: "Solid error disabled.", kind: "color" },
      { name: "--pt-info-t2-fg1-default", value: "#0172B4", description: "Info / link button default.", kind: "color" },
      { name: "--pt-info-t2-fg1-hover", value: "#015687", description: "Info / link button hover.", kind: "color" },
      { name: "--pt-info-t2-fg1-press", value: "#00395A", description: "Info / link button press.", kind: "color" },
      { name: "--pt-info-t2-fg1-disable", value: "#99D2F3", description: "Info / link button disabled.", kind: "color" },
      { name: "--pt-neutral-t1-bg1-default", value: "#FFFFFF", description: "Product neutral surface.", kind: "color" },
      { name: "--pt-neutral-t1-st5-default", value: "#E6E6E6", description: "Product subtle stroke.", kind: "color" },
      { name: "--pt-neutral-t1-fg2-default", value: "#4C4C4C", description: "Product secondary foreground.", kind: "color" },
      { name: "--pt-neutral-t1-st2-disable", value: "#cccccc", description: "Product disabled stroke.", kind: "color" },
    ],
  },
  {
    slug: "typography",
    title: "Typography",
    description: "Font sizes, weights, line heights, and letter spacing.",
    group: "Foundations",
    tokens: [
      { name: "--font-weight-regular", value: "400", description: "Regular body weight.", kind: "type" },
      { name: "--font-weight-medium", value: "450", description: "Medium weight (e.g. pagination).", kind: "type" },
      { name: "--font-weight-medium-500", value: "500", description: "Numeric medium weight (e.g. card meta labels).", kind: "type" },
      { name: "--font-weight-semibold", value: "600", description: "Semibold labels and titles.", kind: "type" },
      { name: "--type-letter-spacing-tight", value: "-0.02em", description: "Default tight tracking (-2%).", kind: "type" },
      { name: "--type-letter-spacing-wide", value: "0.04em", description: "Wide tracking (e.g. nav captions).", kind: "type" },
      { name: "--type-label-font-size", value: "14px", description: "Field label size.", kind: "type" },
      { name: "--type-label-line-height", value: "20px", description: "Field label line height.", kind: "type" },
      { name: "--type-label-font-weight", value: "var(--font-weight-regular)", description: "Field label weight.", kind: "type" },
      { name: "--type-label-letter-spacing", value: "var(--type-letter-spacing-tight)", description: "Field label tracking.", kind: "type" },
      { name: "--type-input-font-size", value: "14px", description: "Input value size.", kind: "type" },
      { name: "--type-input-line-height", value: "20px", description: "Input value line height.", kind: "type" },
      { name: "--type-input-font-weight", value: "var(--font-weight-regular)", description: "Input value weight.", kind: "type" },
      { name: "--type-input-letter-spacing", value: "var(--type-letter-spacing-tight)", description: "Input value tracking.", kind: "type" },
      { name: "--type-message-font-size", value: "12px", description: "Helper / error message size.", kind: "type" },
      { name: "--type-message-line-height", value: "16px", description: "Helper / error message line height.", kind: "type" },
      { name: "--type-message-font-weight", value: "var(--font-weight-semibold)", description: "Helper / error message weight.", kind: "type" },
      { name: "--type-message-letter-spacing", value: "var(--type-letter-spacing-tight)", description: "Helper / error message tracking.", kind: "type" },
      { name: "--type-compact-font-size", value: "13px", description: "Compact body size (cards, dense UI).", kind: "type" },
      { name: "--type-compact-line-height", value: "18px", description: "Compact body line height.", kind: "type" },
      { name: "--type-title-font-size", value: "18px", description: "Shared title size (login / modal titles).", kind: "type" },
      { name: "--type-title-line-height", value: "24px", description: "Shared title line height.", kind: "type" },
      { name: "--type-heading-font-size", value: "16px", description: "Section / docs heading size.", kind: "type" },
      { name: "--type-heading-line-height", value: "24px", description: "Section / docs heading line height.", kind: "type" },
      { name: "--type-caption-font-size", value: "11px", description: "Uppercase caption / nav group size.", kind: "type" },
      { name: "--type-body-relaxed-line-height", value: "22px", description: "Relaxed body line height (guides).", kind: "type" },
    ],
  },
  {
    slug: "spacing",
    title: "Spacing",
    description: "Shared spacing scale plus field-specific gaps.",
    group: "Foundations",
    tokens: [
      { name: "--space-4", value: "4px", description: "Spacing scale step 4.", kind: "size" },
      { name: "--space-6", value: "6px", description: "Spacing scale step 6.", kind: "size" },
      { name: "--space-8", value: "8px", description: "Spacing scale step 8.", kind: "size" },
      { name: "--space-10", value: "10px", description: "Spacing scale step 10.", kind: "size" },
      { name: "--space-12", value: "12px", description: "Spacing scale step 12.", kind: "size" },
      { name: "--space-16", value: "16px", description: "Spacing scale step 16.", kind: "size" },
      { name: "--space-18", value: "18px", description: "Spacing scale step 18.", kind: "size" },
      { name: "--space-20", value: "20px", description: "Spacing scale step 20.", kind: "size" },
      { name: "--space-24", value: "24px", description: "Spacing scale step 24.", kind: "size" },
      { name: "--space-28", value: "28px", description: "Spacing scale step 28.", kind: "size" },
      { name: "--space-32", value: "32px", description: "Spacing scale step 32.", kind: "size" },
      { name: "--space-38", value: "38px", description: "Spacing scale step 38.", kind: "size" },
      { name: "--space-40", value: "40px", description: "Spacing scale step 40.", kind: "size" },
      { name: "--space-field-label-gap", value: "var(--space-8)", description: "Gap between label and control.", kind: "size" },
      { name: "--space-field-message-gap", value: "var(--space-8)", description: "Gap between control and message.", kind: "size" },
      { name: "--space-input-padding-x", value: "var(--space-12)", description: "Horizontal input padding.", kind: "size" },
    ],
  },
  {
    slug: "radius",
    title: "Radius",
    description: "Corner radii for fields, badges, and controls.",
    group: "Foundations",
    tokens: [
      { name: "--radius-2", value: "2px", description: "Extra-small radius.", kind: "size" },
      { name: "--radius-4", value: "4px", description: "Small radius (badges, checkbox).", kind: "size" },
      { name: "--radius-6", value: "6px", description: "Medium-small radius (card index, docs swatches).", kind: "size" },
      { name: "--radius-input", value: "8px", description: "Input / field radius (md).", kind: "size" },
      { name: "--radius-button", value: "12px", description: "Button radius.", kind: "size" },
    ],
  },
  {
    slug: "motion",
    title: "Motion",
    description: "Durations and easing for transitions and spinners.",
    group: "Foundations",
    tokens: [
      { name: "--motion-duration-fast", value: "120ms", description: "Hover / press transitions.", kind: "motion" },
      { name: "--motion-easing-standard", value: "ease", description: "Default easing curve.", kind: "motion" },
      { name: "--motion-duration-spin", value: "0.8s", description: "Loading spinner rotation.", kind: "motion" },
    ],
  },
  {
    slug: "elevation",
    title: "Elevation",
    description: "Stacking order and shadows for overlays and panels.",
    group: "Foundations",
    tokens: [
      { name: "--z-sidebar", value: "30", description: "Fixed sidebar layer.", kind: "z" },
      { name: "--z-sidebar-backdrop", value: "34", description: "Mobile nav backdrop.", kind: "z" },
      { name: "--z-sidebar-overlay", value: "35", description: "Mobile drawer sidebar.", kind: "z" },
      { name: "--z-header", value: "40", description: "Fixed header layer.", kind: "z" },
      { name: "--z-modal", value: "50", description: "Modal overlay layer.", kind: "z" },
      { name: "--z-popover", value: "60", description: "Menus / popovers above modals.", kind: "z" },
      { name: "--z-toast", value: "1100", description: "Toast viewport above all chrome.", kind: "z" },
      { name: "--toast-shadow", value: "0px 8px 40px 0px #2533433D", description: "Toast elevation shadow.", kind: "shadow" },
      { name: "--menu-panel-shadow", value: "0px 4px 16px 0px #00000029", description: "Dropdown panel shadow.", kind: "shadow" },
      { name: "--table-actions-menu-shadow", value: "0px 4px 16px rgba(0, 0, 0, 0.16)", description: "Table row actions menu shadow.", kind: "shadow" },
      { name: "--sidebar-drawer-shadow", value: "8px 0 24px rgb(0 0 0 / 16%)", description: "Mobile sidebar drawer shadow (LTR).", kind: "shadow" },
      { name: "--sidebar-drawer-shadow-rtl", value: "-8px 0 24px rgb(0 0 0 / 16%)", description: "Mobile sidebar drawer shadow (RTL).", kind: "shadow" },
      { name: "--docs-card-shadow", value: "0 1px 3px rgb(0 0 0 / 6%)", description: "Docs card / playground shadow.", kind: "shadow" },
    ],
  },
  {
    slug: "input",
    title: "Input",
    description: "Heights and border for text fields.",
    group: "Components",
    tokens: [
      { name: "--input-height-sm", value: "36px", description: "Small field height.", kind: "size" },
      { name: "--input-height-md", value: "40px", description: "Medium field height.", kind: "size" },
      { name: "--input-height-lg", value: "48px", description: "Large field height.", kind: "size" },
      { name: "--input-border-width", value: "1px", description: "Field border width.", kind: "size" },
      { name: "--textarea-min-height", value: "120px", description: "Textarea minimum height.", kind: "size" },
    ],
  },
  {
    slug: "checkbox",
    title: "Checkbox",
    description: "Control size, radius, padding, and label gap.",
    group: "Components",
    tokens: [
      { name: "--checkbox-size", value: "16px", description: "Control box size.", kind: "size" },
      { name: "--checkbox-radius", value: "4px", description: "Control corner radius.", kind: "size" },
      { name: "--checkbox-padding-on", value: "2px", description: "Inner padding when on / indeterminate.", kind: "size" },
      { name: "--checkbox-padding-off", value: "0px", description: "Inner padding when off.", kind: "size" },
      { name: "--checkbox-border-width", value: "2px", description: "Off-state outline width.", kind: "size" },
      { name: "--checkbox-label-gap", value: "4px", description: "Gap between control and label.", kind: "size" },
    ],
  },
  {
    slug: "button",
    title: "Button",
    description: "Height, padding, radius, and border for buttons.",
    group: "Components",
    tokens: [
      { name: "--button-height", value: "40px", description: "Button height.", kind: "size" },
      { name: "--button-padding-y", value: "10px", description: "Vertical padding (text layout).", kind: "size" },
      { name: "--button-padding-x", value: "16px", description: "Horizontal padding (text layout).", kind: "size" },
      { name: "--button-border-width", value: "1px", description: "Secondary border width.", kind: "size" },
      { name: "--radius-button", value: "12px", description: "Button corner radius.", kind: "size" },
    ],
  },
  {
    slug: "toast",
    title: "Toast",
    description: "Toast dimensions, typography, and type-specific min widths.",
    group: "Components",
    tokens: [
      { name: "--toast-min-height", value: "44px", description: "Minimum toast height.", kind: "size" },
      { name: "--toast-padding-y", value: "12px", description: "Vertical padding.", kind: "size" },
      { name: "--toast-padding-x", value: "16px", description: "Horizontal padding.", kind: "size" },
      { name: "--toast-radius", value: "8px", description: "Toast corner radius.", kind: "size" },
      { name: "--toast-title-description-gap", value: "4px", description: "Gap between title and description.", kind: "size" },
      { name: "--toast-min-width-success", value: "121px", description: "Success toast min width.", kind: "size" },
      { name: "--toast-min-width-error", value: "129px", description: "Error toast min width.", kind: "size" },
      { name: "--toast-title-font-size", value: "14px", description: "Title size.", kind: "type" },
      { name: "--toast-title-line-height", value: "20px", description: "Title line height.", kind: "type" },
      { name: "--toast-title-font-weight", value: "var(--font-weight-semibold)", description: "Title weight.", kind: "type" },
      { name: "--toast-title-letter-spacing", value: "var(--type-letter-spacing-tight)", description: "Title tracking.", kind: "type" },
      { name: "--toast-description-font-size", value: "12px", description: "Description size.", kind: "type" },
      { name: "--toast-description-line-height", value: "16px", description: "Description line height.", kind: "type" },
      { name: "--toast-description-font-weight", value: "var(--font-weight-regular)", description: "Description weight.", kind: "type" },
      { name: "--toast-description-letter-spacing", value: "var(--type-letter-spacing-tight)", description: "Description tracking.", kind: "type" },
      { name: "--toast-offset-top-mobile", value: "16px", description: "Top offset on mobile.", kind: "size" },
      { name: "--toast-offset-top-tablet", value: "40px", description: "Top offset on tablet.", kind: "size" },
      { name: "--toast-offset-top-desktop", value: "56px", description: "Top offset on desktop.", kind: "size" },
      { name: "--toast-offset-x-mobile", value: "16px", description: "Horizontal inset for max-width calc.", kind: "size" },
      { name: "--toast-max-width", value: "560px", description: "Toast max width.", kind: "size" },
    ],
  },
  {
    slug: "pagination",
    title: "Pagination",
    description: "Panel metrics, item size, and ellipsis icon metrics. Width is content-driven.",
    group: "Components",
    tokens: [
      { name: "--pagination-radius", value: "8px", description: "Panel radius.", kind: "size" },
      { name: "--pagination-border-width", value: "1px", description: "Panel border width.", kind: "size" },
      { name: "--pagination-padding", value: "4px", description: "Panel padding.", kind: "size" },
      { name: "--pagination-gap", value: "4px", description: "Gap between items.", kind: "size" },
      { name: "--pagination-item-size", value: "32px", description: "Page / chevron item size.", kind: "size" },
      { name: "--pagination-item-radius", value: "8px", description: "Item radius.", kind: "size" },
      { name: "--pagination-item-padding-x", value: "8px", description: "Item horizontal padding.", kind: "size" },
      { name: "--pagination-ellipsis-width", value: "14px", description: "Dots icon width.", kind: "size" },
      { name: "--pagination-ellipsis-height", value: "3.5px", description: "Dots icon height.", kind: "size" },
    ],
  },
  {
    slug: "menu",
    title: "Menu",
    description: "Dropdown item and panel dimensions.",
    group: "Components",
    tokens: [
      { name: "--menu-element-width", value: "243px", description: "Menu item width.", kind: "size" },
      { name: "--menu-item-height", value: "36px", description: "Menu item min height.", kind: "size" },
      { name: "--menu-item-border-radius", value: "8px", description: "Menu item radius.", kind: "size" },
      { name: "--menu-item-padding", value: "8px", description: "Menu item padding.", kind: "size" },
      { name: "--menu-item-gap", value: "8px", description: "Icon / label gap.", kind: "size" },
      { name: "--menu-panel-width", value: "287px", description: "Dropdown panel width.", kind: "size" },
      { name: "--menu-panel-radius", value: "12px", description: "Panel radius.", kind: "size" },
      { name: "--menu-panel-padding", value: "8px", description: "Panel padding.", kind: "size" },
      { name: "--menu-panel-gap", value: "4px", description: "Gap between panel children.", kind: "size" },
    ],
  },
  {
    slug: "modal",
    title: "Modal",
    description: "Overlay, panel, header, body, footer, and status icon tokens.",
    group: "Components",
    tokens: [
      { name: "--modal-overlay-bg", value: "#00000052", description: "Scrim behind the panel.", kind: "color" },
      { name: "--modal-radius", value: "8px", description: "Panel radius.", kind: "size" },
      { name: "--modal-border-width", value: "1px", description: "Header / footer divider width.", kind: "size" },
      { name: "--modal-header-height", value: "72px", description: "Header height.", kind: "size" },
      { name: "--modal-header-padding-y", value: "16px", description: "Header vertical padding.", kind: "size" },
      { name: "--modal-header-padding-x", value: "24px", description: "Header horizontal padding.", kind: "size" },
      { name: "--modal-body-max-height", value: "456px", description: "Body max height before scroll.", kind: "size" },
      { name: "--modal-body-padding", value: "24px", description: "Body padding.", kind: "size" },
      { name: "--modal-footer-height", value: "72px", description: "Footer height.", kind: "size" },
      { name: "--modal-footer-padding-y", value: "16px", description: "Footer vertical padding.", kind: "size" },
      { name: "--modal-footer-padding-x", value: "24px", description: "Footer horizontal padding.", kind: "size" },
      { name: "--modal-footer-gap", value: "12px", description: "Gap between footer actions.", kind: "size" },
      { name: "--modal-icon-wrapper-size", value: "56px", description: "Status icon circle size.", kind: "size" },
      { name: "--modal-icon-wrapper-padding", value: "16px", description: "Status icon circle padding.", kind: "size" },
      { name: "--modal-icon-wrapper-radius", value: "96px", description: "Status icon circle radius.", kind: "size" },
      { name: "--modal-icon-size", value: "24px", description: "Glyph size inside the circle.", kind: "size" },
      { name: "--modal-viewport-gutter", value: "var(--space-32)", description: "Horizontal gutter subtracted from viewport width.", kind: "size" },
      { name: "--modal-viewport-gutter-compact", value: "var(--space-16)", description: "Backdrop inset for mobile and tablet bottom placement.", kind: "size" },
    ],
  },
  {
    slug: "section",
    title: "Section",
    description: "Section card width, padding, and divider.",
    group: "Components",
    tokens: [
      { name: "--section-width", value: "810px", description: "Default section width.", kind: "size" },
      { name: "--section-header-min-height", value: "92px", description: "Header min height.", kind: "size" },
      { name: "--section-body-height", value: "256px", description: "Body min height.", kind: "size" },
      { name: "--section-padding", value: "24px", description: "Header / body padding.", kind: "size" },
      { name: "--section-title-description-gap", value: "8px", description: "Title to description gap.", kind: "size" },
      { name: "--section-radius", value: "8px", description: "Card radius.", kind: "size" },
      { name: "--section-border-width", value: "1px", description: "Header divider width.", kind: "size" },
    ],
  },
  {
    slug: "sidebar",
    title: "Sidebar",
    description: "Sidebar rail and item sizing.",
    group: "Components",
    tokens: [
      { name: "--sidebar-width", value: "240px", description: "Sidebar width.", kind: "size" },
      { name: "--sidebar-padding", value: "16px", description: "Sidebar padding.", kind: "size" },
      { name: "--sidebar-item-width", value: "216px", description: "Item width.", kind: "size" },
      { name: "--sidebar-item-min-height", value: "40px", description: "Item min height.", kind: "size" },
      { name: "--sidebar-item-padding", value: "8px", description: "Item padding.", kind: "size" },
      { name: "--sidebar-border-width", value: "1px", description: "Sidebar edge border.", kind: "size" },
      { name: "--sidebar-drawer-shadow", value: "8px 0 24px rgb(0 0 0 / 16%)", description: "Mobile drawer shadow (LTR).", kind: "shadow" },
      { name: "--sidebar-drawer-shadow-rtl", value: "-8px 0 24px rgb(0 0 0 / 16%)", description: "Mobile drawer shadow (RTL).", kind: "shadow" },
    ],
  },
  {
    slug: "header",
    title: "Header",
    description: "App header height, padding, and gap.",
    group: "Components",
    tokens: [
      { name: "--header-height", value: "64px", description: "Header height.", kind: "size" },
      { name: "--header-padding-y", value: "12px", description: "Vertical padding.", kind: "size" },
      { name: "--header-padding-x", value: "24px", description: "Horizontal padding.", kind: "size" },
      { name: "--header-border-width", value: "1px", description: "Bottom border width.", kind: "size" },
      { name: "--header-gap", value: "16px", description: "Gap between header slots.", kind: "size" },
    ],
  },
  {
    slug: "table",
    title: "Table",
    description: "Row height, typography, row number badge, and actions menu.",
    group: "Components",
    tokens: [
      { name: "--table-row-height", value: "48px", description: "Header and body row height.", kind: "size" },
      { name: "--table-header-bg", value: "var(--neutral-bg1-hover)", description: "Header background.", kind: "color" },
      { name: "--table-stroke", value: "var(--neutral-st3-default)", description: "Row / header divider color.", kind: "color" },
      { name: "--table-stroke-width", value: "1px", description: "Divider width.", kind: "size" },
      { name: "--table-row-bg", value: "var(--neutral-bg1-default)", description: "Body row background.", kind: "color" },
      { name: "--table-row-number-bg", value: "var(--neutral-bg1-hover)", description: "Row number badge fill.", kind: "color" },
      { name: "--table-row-number-radius", value: "4px", description: "Row number badge radius.", kind: "size" },
      { name: "--table-row-number-size", value: "28px", description: "Row number badge size.", kind: "size" },
      { name: "--table-row-number-padding-x", value: "8px", description: "Row number horizontal padding.", kind: "size" },
      { name: "--table-header-font-size", value: "18px", description: "Header text size.", kind: "type" },
      { name: "--table-header-line-height", value: "24px", description: "Header line height.", kind: "type" },
      { name: "--table-header-font-weight", value: "var(--font-weight-semibold)", description: "Header text weight.", kind: "type" },
      { name: "--table-header-letter-spacing", value: "var(--type-letter-spacing-tight)", description: "Header tracking.", kind: "type" },
      { name: "--table-cell-font-size", value: "14px", description: "Body cell text size.", kind: "type" },
      { name: "--table-cell-line-height", value: "20px", description: "Body cell line height.", kind: "type" },
      { name: "--table-cell-font-weight", value: "var(--font-weight-regular)", description: "Body cell weight.", kind: "type" },
      { name: "--table-cell-strong-font-weight", value: "var(--font-weight-semibold)", description: "Emphasized cell weight.", kind: "type" },
      { name: "--table-cell-letter-spacing", value: "var(--type-letter-spacing-tight)", description: "Body cell tracking.", kind: "type" },
      { name: "--table-cell-padding-x", value: "16px", description: "Cell horizontal padding.", kind: "size" },
      { name: "--table-actions-trigger-size", value: "32px", description: "Options button size.", kind: "size" },
      { name: "--table-actions-trigger-border-width", value: "1px", description: "Options button border width.", kind: "size" },
      { name: "--table-actions-trigger-radius", value: "12px", description: "Options button radius.", kind: "size" },
      { name: "--table-actions-menu-width", value: "144px", description: "Actions menu width.", kind: "size" },
      { name: "--table-actions-menu-height", value: "90px", description: "Actions menu height.", kind: "size" },
      { name: "--table-actions-menu-padding", value: "8px", description: "Actions menu padding.", kind: "size" },
      { name: "--table-actions-menu-gap", value: "4px", description: "Actions menu item gap.", kind: "size" },
      { name: "--table-actions-menu-radius", value: "12px", description: "Actions menu radius.", kind: "size" },
      { name: "--table-actions-menu-edge", value: "8px", description: "Menu offset from viewport edge.", kind: "size" },
      { name: "--table-actions-menu-shadow", value: "0px 4px 16px rgba(0, 0, 0, 0.16)", description: "Actions menu shadow.", kind: "shadow" },
    ],
  },
  {
    slug: "login",
    title: "Login",
    description: "Login page, card, header, and typography tokens.",
    group: "Components",
    tokens: [
      { name: "--login-page-bg", value: "#f0f0f0", description: "Login page background.", kind: "color" },
      { name: "--login-page-padding-tablet", value: "var(--space-24)", description: "Page padding from tablet up.", kind: "size" },
      { name: "--login-page-padding-desktop", value: "var(--space-40)", description: "Page padding from desktop up.", kind: "size" },
      { name: "--login-card-width", value: "480px", description: "Card max width on tablet+.", kind: "size" },
      { name: "--login-card-radius", value: "8px", description: "Card corner radius on tablet+.", kind: "size" },
      { name: "--login-card-bg", value: "#ffffff", description: "Card background.", kind: "color" },
      { name: "--login-header-padding-y", value: "var(--space-38)", description: "Card header vertical padding.", kind: "size" },
      { name: "--login-header-padding-x", value: "var(--space-24)", description: "Card header horizontal padding.", kind: "size" },
      { name: "--login-body-padding", value: "var(--space-24)", description: "Card body padding.", kind: "size" },
      { name: "--login-fields-gap", value: "var(--space-12)", description: "Gap between fields.", kind: "size" },
      { name: "--login-title-font-size", value: "18px", description: "Login title size.", kind: "type" },
      { name: "--login-footer-font-size", value: "14px", description: "Footer text size.", kind: "type" },
    ],
  },
  {
    slug: "dashboard",
    title: "Dashboard",
    description: "Dashboard shell layout and header chrome tokens.",
    group: "Components",
    tokens: [
      { name: "--dashboard-page-bg", value: "#f0f0f0", description: "Dashboard page background.", kind: "color" },
      { name: "--dashboard-content-padding", value: "var(--space-24)", description: "Main content padding.", kind: "size" },
      { name: "--dashboard-content-gap", value: "var(--space-24)", description: "Main content gap.", kind: "size" },
      { name: "--dashboard-header-start-gap", value: "var(--space-12)", description: "Gap in header start cluster.", kind: "size" },
      { name: "--dashboard-center-label-padding-y", value: "var(--space-6)", description: "Center brand label vertical padding.", kind: "size" },
      { name: "--dashboard-center-label-padding-x", value: "var(--space-12)", description: "Center brand label horizontal padding.", kind: "size" },
      { name: "--dashboard-center-label-radius", value: "var(--radius-input)", description: "Center brand label radius.", kind: "size" },
      { name: "--dashboard-header-padding-x-tablet", value: "var(--space-16)", description: "Header inline padding on tablet.", kind: "size" },
      { name: "--dashboard-header-padding-x-mobile", value: "var(--space-12)", description: "Header inline padding on mobile.", kind: "size" },
    ],
  },
  {
    slug: "articles",
    title: "Articles",
    description: "Articles list, cards, and create/edit form layout tokens.",
    group: "Components",
    tokens: [
      { name: "--articles-header-padding-y", value: "var(--space-38)", description: "Section header vertical padding.", kind: "size" },
      { name: "--articles-header-padding-x", value: "var(--space-24)", description: "Section header horizontal padding.", kind: "size" },
      { name: "--articles-body-padding", value: "var(--space-24)", description: "Section body padding.", kind: "size" },
      { name: "--articles-content-gap", value: "var(--space-16)", description: "Gap between table and pagination.", kind: "size" },
      { name: "--articles-table-min-width", value: "760px", description: "Desktop table min width.", kind: "size" },
      { name: "--articles-card-radius", value: "var(--radius-input)", description: "Mobile card radius.", kind: "size" },
      { name: "--articles-card-index-radius", value: "var(--radius-6)", description: "Card index badge radius.", kind: "size" },
      { name: "--articles-form-tags-width", value: "376px", description: "Tags panel width on desktop.", kind: "size" },
      { name: "--articles-form-tags-list-max-height", value: "360px", description: "Tags list scroll max height.", kind: "size" },
      { name: "--articles-delete-status-gap", value: "var(--space-16)", description: "Delete modal status stack gap.", kind: "size" },
    ],
  },
  {
    slug: "docs",
    title: "Docs",
    description: "Internal docs site surfaces (playground stages, guides).",
    group: "Components",
    tokens: [
      { name: "--docs-page-bg", value: "#e8e8e8", description: "Docs shell background.", kind: "color" },
      { name: "--docs-stage-bg", value: "#dddddd", description: "Playground / examples stage background.", kind: "color" },
      { name: "--docs-table-header-bg", value: "#f5f5f5", description: "API table header background.", kind: "color" },
      { name: "--docs-card-shadow", value: "0 1px 3px rgb(0 0 0 / 6%)", description: "Docs card shadow.", kind: "shadow" },
      { name: "--docs-inline-code-bg", value: "rgb(0 0 0 / 6%)", description: "Inline code chip background.", kind: "color" },
      { name: "--docs-content-padding", value: "var(--space-24)", description: "Docs main padding.", kind: "size" },
      { name: "--docs-guide-max-width", value: "720px", description: "Guide article max width.", kind: "size" },
      { name: "--docs-token-swatch-size", value: "28px", description: "Token color swatch size.", kind: "size" },
    ],
  },
] as const;

export function getTokenCategory(slug: string): TokenCategory | undefined {
  return TOKEN_NAV.find((item) => item.slug === slug);
}

export function isTokenSlug(slug: string): slug is TokenCategorySlug {
  return TOKEN_NAV.some((item) => item.slug === slug);
}

export const TOKEN_FOUNDATIONS = TOKEN_NAV.filter((t) => t.group === "Foundations");
export const TOKEN_COMPONENTS = TOKEN_NAV.filter((t) => t.group === "Components");
